#!/bin/bash

# THIS SCRIPT REQUIRES fzf, pbcopy, pbpaste TO BE INSTALLED
#
# 1. add alias fzfcopy='PATH_TO_THIS_SCRIPT/fzfcopy'
# to your .zshrc or .bashrc or any of your shell configuration file and restart
# your shell
# 2. goto target directory and type `echo $(pwd) | pbcopy`
# 3. type fzfcopy and select files to copy (pressing tab by default)
# 4. type enter
# 5. selected files will be copied to target directory
cp -r $(find . -d | fzf -m) $(pbpaste)
